<?php

$labels = array();

$labels['otp_label'] = 'OTP';
$labels['invalid_otp'] = 'Sorry, the OTP you entered is incorrect!';
$labels['invalid_phone'] = 'Invalid phone number';
$labels['otp_message'] = 'OTP $otp';
$labels['phone_label'] = 'Phone Number';
$labels['submit_button'] = 'Submit';
$labels['validate_button'] = 'Validate';
$labels['otp_enabled'] = 'OTP enabled';
$labels['otp_description'] = 'When activating the additional security mechanism, you will have to enter your phone number at the next login, and at each subsequent login you will receive a security otp token via SMS, which is valid for only 5 minutes.';