<?php

$labels = array();

$labels['otp_label'] = 'Varnostna koda';
$labels['invalid_otp'] = 'Oprostite, vnešena varnostna koda je napačna!';
$labels['invalid_phone'] = 'Neveljavna telefonska številka!';
$labels['otp_message'] = 'Vaš varnostni otp žeton je $otp, ta pa je veljaven le 5 minut.';
$labels['phone_label'] = 'Telefonska številka';
$labels['submit_button'] = 'Shrani';
$labels['validate_button'] = 'Potrdi';
$labels['otp_enabled'] = 'OTP dvostopenjska avtentifikacija';
$labels['otp_description'] = 'Ob aktivaciji dodatnega varnostnega mehanizma boste morali ob naslednji prijavi vnesti vašo telefonsko številko (npr. 031222444, ob vsaki naslednji prijavi pa boste preko sms sporočila dobili varnostni otp žeton (6 števil), ki je veljaven zgolj le 5 minut. Ob izteku časovne omejitve je potrebno stran osvežiti in prejeli boste nov otp (sms sporočilo) varnostni žeton.';